default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: RkumarS123
  host: localhost
  socket: mysql

development:
  <<: *default
  database: letsshop_development

test:
  <<: *default
  database: letsshop_test

production:
  <<: *default
  database: letsshop_production
